spring.cloud.config.server.git.uri:"https://github.com/ldeeley/rocknrollConfigService.git"
server.port:8888

my.greeting:"A message from config server"

db:connection:"connection string..."
   host:127.0.0.1
   port:8080